/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#6f88ad',
        'on-secondary-container': '#556474',
        'tertiary-fixed-dim': '#66dd8b',
        'surface-variant': '#e3e2e5',
        'outline': '#74777f',
        'on-primary': '#ffffff',
        'on-primary-fixed-variant': '#2f486a',
        'inverse-surface': '#2f3033',
        'tertiary-fixed': '#83fba5',
        'surface-container': '#efedf0',
        'secondary-fixed': '#d4e4f6',
        'background': '#faf9fc',
        'secondary': '#50606f',
        'on-secondary-fixed': '#0d1d2a',
        'inverse-primary': '#afc8f0',
        'surface-bright': '#faf9fc',
        'outline-variant': '#c4c6cf',
        'on-tertiary-container': '#119b50',
        'on-secondary-fixed-variant': '#394857',
        'surface-container-high': '#e9e7eb',
        'tertiary': '#000802',
        'on-tertiary-fixed-variant': '#005227',
        'primary-fixed-dim': '#afc8f0',
        'tertiary-container': '#00250e',
        'surface': '#faf9fc',
        'on-error': '#ffffff',
        'primary-container': '#001f3f',
        'on-background': '#1a1c1e',
        'on-secondary': '#ffffff',
        'error-container': '#ffdad6',
        'secondary-container': '#d1e1f4',
        'on-tertiary-fixed': '#00210c',
        'primary': '#000613',
        'surface-dim': '#dbd9dd',
        'surface-container-low': '#f4f3f6',
        'error': '#ba1a1a',
        'surface-container-highest': '#e3e2e5',
        'on-error-container': '#93000a',
        'secondary-fixed-dim': '#b8c8da',
        'on-surface': '#1a1c1e',
        'on-primary-fixed': '#001c3a',
        'surface-container-lowest': '#ffffff',
        'on-surface-variant': '#43474e',
        'on-tertiary': '#ffffff',
        'inverse-on-surface': '#f2f0f3',
        'primary-fixed': '#d4e3ff',
        'surface-tint': '#476083',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        md: '16px',
        'container-max': '1200px',
        gutter: '16px',
        unit: '8px',
        margin: '24px',
        xl: '32px',
        lg: '24px',
        sm: '8px',
        xs: '4px',
      },
      fontFamily: {
        'body-md': ['Manrope', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'data-mono': ['Manrope', 'sans-serif'],
        'label-bold': ['Manrope', 'sans-serif'],
        h3: ['Manrope', 'sans-serif'],
        h1: ['Manrope', 'sans-serif'],
        h2: ['Manrope', 'sans-serif'],
        'body-sm': ['Manrope', 'sans-serif'],
        manrope: ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'data-mono': ['16px', { lineHeight: '1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-bold': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
        h3: ['20px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        h1: ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
